on: [workflow_dispatch]

jobs:
  testbox:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/smas-docker/eiffel-builder-19.05:202101290755
    steps:  
      - name: What OS is running
        run: uname -a
      - name: Show contents of eiffel library path
        run: ls -al $ISE_LIBRARY
      - name: Show contents of eiffel library path
        run: ls -al $MYSQLINC
