on: [workflow_dispatch]

jobs:
  testbox:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/smas-docker/eiffel-builder-19.05:202101290755
    steps:  
      - name: What OS is running
        run: uname -a
      - name: Show contents of checkout
        run: ls -al $ISE_EIFFEL
